[package]
name = "bezier"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
glium = "0.15.0"
imgui = "0.0.10"
imgui-sys = "0.0.10"
cgmath = "0.12.0"
regex = "0.1.80"
docopt = "0.6.86"
rustc-serialize = "0.3.19"
num-traits = "0.1.36"
rulinalg = "0.3.7"

